### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by howderek** [OSSHealth/ghdata#14]
We need to support CI. We will probably use Travis.

Some challenges include:
  - Testing against a large database hosted elsewhere
  - Testing commands that will have different results since it works with realtime data
  - Testing the initialization of the database

Tests are not the highest priority right now, but should be supported before 1.0.0

**Comment by germonprez** [comment]
Yes. I 100% agree with this one. A few other tests might include if we connect to external systems for license and vulnerability issues.

**Comment by abuhman** [comment]
For unit testing, unittest (also known as pyUnit) could be a good choice.  It is included in Python standard libraries.

Documentation:
https://docs.python.org/2/library/unittest.html

unittest is also used in Django for testing:
https://docs.djangoproject.com/en/1.10/topics/testing/

It's a good idea to create unit tests early on, as it will be much easier to implement them at the same time as the code than to go back later and try to add unit tests to code that was not set up to accommodate them.  It will also help to determine whether anything has broken due to a change, and serve as extra documentation for how things are expected to work (assuming the tests are kept up-to-date with the code)

**Comment by ChristianCme** [comment]
I just added some basic unit tests for the library functions using pytest to the repo. Are those good for the baseline library functions? I'm also working on a travis.yml to add as well

**Comment by abuhman** [comment]
Thanks for the tests!  Could you please comment and indicate what the tests are doing and how they demonstrate that things are working?  

For example, you have this test:

def test_commits(gh):
    assert gh.commits('8').isin(["2013-01-07"]).any

My best guess is that you are asserting that repo id 8 made at least 1 commit on 2013-01-07 (which you likely pre-checked in msr14 database to find a repo with commits for that day), and you are doing this test in order to demonstrate that the commits function is returning an expected result for this query.  Is that the case?

**Comment by ChristianCme** [comment]
Yep, that's right! I'll get the comments in later today. Also, our Travis build is successful with 3.6, but not 2.7. I'll look into that as well

**Comment by abuhman** [comment]
Ok thanks

**Comment by ChristianCme** [comment]
I added some comments in test_ghdata.py to give the general format for my tests. Let me know if I need to go into more detail. Also the 3.6 build is passing. There are issues with pytest and 2.7, but travis is messed up because of the AWS outage, so I'll get it fixed as soon as I can.
