### ISSUE TITLE
Google BigQuery with GitHub data

### ISSUE THREAD

**Issue by GeorgLink** [OSSHealth/ghdata#17]
Today, Patrick from eBay pointed us to [Google BigQuery](https://cloud.google.com/bigquery/public-data/github) because they have the [GitHub Archive](https://www.githubarchive.org/#bigquery) dataset and can run large queries in short amount of times.

[One idea what could be done](https://cloudplatform.googleblog.com/2016/06/GitHub-on-BigQuery-analyze-all-the-open-source-code.html):
> For example, let's say you're the author of a popular open source library. Now you'll be able to find every open source project on GitHub that's using it.

Another example combines datasets to show the [effect of Hacker News on the stars of a project](https://medium.com/google-cloud/big-data-stories-in-seconds-hacker-news-abe52bc5caad#.usgh8qj5o) (how well is the PR working?)

I leave the exploration, whether this is useful to our able programmers :-)

**Comment by germonprez** [comment]
@abuhman, I'd be interested in seeing how your queries fair against Google BigQuery.

**Comment by howderek** [comment]
@germonprez The consideration we need to make with BigQuery is that we have to pay for the queries after 1TB. Once we get the dataset downloaded to our own server we shouldn't have to pay anyone else to query it.

**Comment by abuhman** [comment]
I think they'd have to be modified before they could run against BigQuery due to a different database schema.  Found a schema here https://github.com/igrigorik/githubarchive.org/blob/master/bigquery/schema.js

**Comment by germonprez** [comment]
Got it. It also doesn't look like the full dataset. Is that the case?

On Feb 15, 2017 9:35 AM, "abuhman" <notifications@github.com> wrote:

I think they'd have to be modified before they could run against BigQuery
due to a different database schema. Found a schema here
https://github.com/igrigorik/githubarchive.org/blob/master/
bigquery/schema.js

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/OSSHealth/ghdata/issues/17#issuecomment-280080696>, or mute
the thread

**Comment by howderek** [comment]
@germonprez GitHub Archive is the raw events from GitHub. GHTorrent includes metadata about those events from the GitHub API

**Comment by howderek** [comment]
I just found out that BigQuery also has the GHTorrent dataset - we should move, this massively lowers the barrier to entry for people who want to use our Python library

**Comment by GeorgLink** [comment]
The [issue "Diversity by nationality"](https://github.com/OSSHealth/HealthIndicators/issues/20) is related.
