### ISSUE TITLE
ghdata.cfg options are not handled well

### ISSUE THREAD

**Issue by howderek** [OSSHealth/ghdata#20]
When a new parameter needs to be added to ghdata.cfg, the entire file has to be regenerated or the new options have to be appended by hand. 

Ideally, all options should be optional and if they don't appear in ghdata.cfg, they should be added automatically with a sensible default.

I totally take responsibility for causing this bug, and I'll fix it myself eventually if no one else does but wanted to make a more accessible way to contribute available publicly in case anyone else wants to tackle it.

**Comment by abuhman** [comment]
That sounds similar to other environment files I have seen in the past. I think this is standard as far as I know.  It's because users can't really put things like their database password on shared code, and since local environments are going to vary.  I think the main thing is letting people know if they need to update and how, I think.
