### ISSUE TITLE
Looking to work on front end

### ISSUE THREAD

**Issue by srobins259** [OSSHealth/ghdata#26]
Hey GHData community,

I would like to build some additional front-end capabilities for your repo. How would you recommend my partner and I begin? We are fairly new to open source, so any guidance would be greatly appreciated! A good start may just be a more detailed description of how to get the front end that you already have up and running.

Thanks,
srobins259 and VRRobbie

**Comment by GeorgLink** [comment]
Hi @srobins259 and VRRobbie,

Welcome to OSSHealth/ghdata!

@abuhman and @howderek can help you find your way around the code base.

Also, take a look at the list of health indicators and their descriptions in [OSSHealth/HealthIndicators](https://github.com/OSSHealth/HealthIndicators/blob/master/CCCIndicators.md). Feel free to open issues there if you have questions about a health indicator that you plan to visualize in the front-end.

**Comment by howderek** [comment]
Hello @srobins259 and @VRRobbie!

First, you'll need a server that can serve static files and MySQL.

Second, you'll need to load the [msr14 dataset](http://ghtorrent.org/msr14.html) into a new database.

Third, you'll need to get GHData configured. `pip install --upgrade https://github.com/OSSHealth/ghdata/archive/dev.zip` then run `ghdata`

A configuration file should be created. Edit that file with your database settings, and set the developer key to one to enable the debugging tools.

Fourth, configure your webserver to serve the files in frontend. I like to use Apache virtual hosts and my /etc/hosts file so that gh.dev gets routed to frontend.

Lastly, run `ghdata` to start the server, and go to your localhost/?owner=cakephp&repo=cakephp

Two graphs should appear. Let me know if you run into any trouble!

The biggest way you could contribute is by developing more visualizations with D3.js, let me know if you need dummy data.

Welcome, and thanks so much!

**Comment by srobins259** [comment]
We have ghdata up and running as a server, but we are still having trouble with the front-end part. Could you explain in a little bit greater detail about the Apache virtual host step?

Thanks,
srobins259

**Comment by howderek** [comment]
@srobins259 It's not required to use Apache VirtualHosts, that's just how I do it. There's a pretty minimal example of how to use development domain names here: https://blogs.fsfe.org/samtuke/?p=359

The most important part is running it on a server locally and not just opening the index.html file directly.

The easiest way to get started is navigating to the frontend directory and running `python -m SimpleHTTPServer` in a terminal

**Comment by srobins259** [comment]
Ok, I have it working now, so we should be able to get started! We will probably start with a basic form entry to input the project owner and repository.

Thanks for the help!
srobins259 and VRRobbie

**Comment by howderek** [comment]
For sure! I look forward to seeing it!
