### ISSUE TITLE
Watchers, stargazers, starring a repo

### ISSUE THREAD

**Issue by abuhman** [OSSHealth/ghdata#43]
Do stargazers, watchers, and starring a repo mean the same thing?

This code and the comments use different terms for what the query is getting.  If, for example, I was to link or copy/paste this code to the "watchers" metric on the wiki, would that be correct?

    # Basic timeseries queries
    def stargazers(self, repoid, start=None, end=None):
        """
        Timeseries of when people starred a repo
        :param repoid: The id of the project in the projects table. Use repoid() to get this.
        :return: DataFrame with stargazers/day
        """
        stargazersSQL = s.sql.text(self.__single_table_count_by_date('watchers', 'repo_id'))
        return pd.read_sql(stargazersSQL, self.db, params={"repoid": str(repoid)})

**Comment by howderek** [comment]
Yeah, so the table name in GHTorrent is watchers because that's what GitHub originally called it, but now they have renamed it to starring. Stargazers are people who have starred a repo. Here's the information from GitHub: [API docs](https://developer.github.com/v3/activity/starring/) and [a blog post](https://github.com/blog/1204-notifications-stars)

Sorry for the confusion!

**Comment by sgoggins** [comment]
Is this issue still open?

**Comment by howderek** [comment]
Yes, it was resolved.
