### ISSUE TITLE
Source Code Structure 

### ISSUE THREAD

**Issue by germonprez** [OSSHealth/ghdata#6]
Could we come up with a better structure for the source code? Not a fan of dumping the .py source on the top level. 

src
install
tests

Something simple like this. 

Also, I'd highly, highly recommend consistent and detailed code commenting.

**Comment by howderek** [comment]
The Hitchhiker's Guide to Python by Kenneth Rietz [recommends not putting the main source in an "ambiguous src folder"](http://docs.python-guide.org/en/latest/writing/structure/) and most large projects put the main source in a folder by the same name as the project. Kenneth Rietz suggests putting the source at the top level if it is only a (single python module)[https://github.com/kennethreitz/records]. If we change the structure, I believe it should look like:

ghdata (instead of src)
tests

and the install will be handled by setup.py in the root folder.

**Comment by germonprez** [comment]
100% agree on ghdata vs. src

Is the setup.py for the application or the database schema?

**Comment by howderek** [comment]
@germonprez the application. So far we don't differ in db schema from GHTorrent, and when we do create a new schema it will probably be implemented with SQLAlchemy so it should be opaque to the user. If we end up creating something that needs an install script we can put it in the install folder like you suggest.

**Comment by howderek** [comment]
@germonprez I'll go ahead and close this issue (I hadn't closed it yet because tests are not yet implemented) but will create a new issue for tests.
